# Generated by Django 4.2.7 on 2023-11-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afisha',
            name='chapter',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
